# Multi-term REACLIB fitting for the Ha96c table

input = Reaclib_Ha96c.dat
terms = terms.txt

# Global reaction information
A1 = 4
A2 = 14
Z1 = 2
Z2 = 8
Threshold = 5.114

# Optional settings
#tmin = 0.23
#plot_tmin = 0.1
#plot_tmax = 10
compare = Reaclib_Ha96c.fit
#output = Ha96c.fit
